# Generated by Django 6.0.5 on 2026-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='task_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
