# Generated by Django 6.0.5 on 2026-06-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_at',
            new_name='published_at_live',
        ),
    ]
